name = "skylogged"
author = "Vercte"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0329110c8917083d226517ac84b22e1b47eaa25055e4111f58dc9d7ef3c3ed4e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"

[options]
acceptable-game-versions = ["1.21"]
