name = "skylogged"
author = "Vercte"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ebec0f8d5e0a6e6ebcc6a93c24f68f2b7fc5be388b05b6bebe8734419b9f07f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"

[options]
acceptable-game-versions = ["1.21"]
